### ISSUE TITLE
Certain HTML Tags not supported.

### ISSUE THREAD

**Issue by JustBuddy** [BlackStartx/VRC-Gesture-Manager#12]
(Version 3.7 and earlier)
The Emulator isn't simulating some menu formattings correctly.

Expected look:
![image](https://user-images.githubusercontent.com/8122264/196724772-16903dd5-c384-4a8b-89f4-7241abda853f.png)

How the emulator renders it:
![image](https://user-images.githubusercontent.com/8122264/196724583-8b5826e1-2976-425c-9677-9f7271e3abfa.png)

The string itself:
`<b><size=23><line-height=100%><voffset=24.5em>Buddy Menu v2</b>`

**Comment by BlackStartx** [comment]
Hi JustBuddy, thanks for the report! ♥

In 2021 I did receive a similar issue (#2) that lead me to implement the commonest TMP formatting tags into the Radial Menu.
I currently **handle** but skip the behaviour of tags like `voffset`, `sup` and `sub` while completely ignoring tags like `line-height`.

But I guess after one year it's finally time to implement those tags as well~ ^-^

I will work on an implementation soon and publish a preview package here once the feature is done, and... sorry for not having it implemented since the begining~ 🌺 

P.S: Also, thanks so much for the string template so I don't have to create a test string myself~ ;3

**Comment by JustBuddy** [comment]
Lovely, looking forward to the implementation. ^^

I'm not sure if "size" is actually handled by the game, I just copied that string from Franadas GoGo Loco.

**Comment by BlackStartx** [comment]
Hi JustBuddy~

Sorry if this response took two weeks but I was mainly focused on other projects~ ^-^'
By the way I took time to enhance the feature a bit so that the text wont look that scuffed :3

I was also working on the v-offset tag, but for now it's too scuffed and I don't like it.
Meanwhile I will drop here a version that handle the whole situation better~

Thanks once again~ 🌺

[GestureManager3.7.zip](https://github.com/BlackStartx/VRC-Gesture-Manager/files/9924671/GestureManager3.7.zip)

P.S: I'm not sure if I should support voffset since the proportion are not the same in-game and it may require a bit ot tweaking.
P.P.S: I also may leave this issue open so that i can get feedback if I should support it or not~ ^-^ ♥

**Comment by JustBuddy** [comment]
> Thanks once again~ 🌺

![image](https://user-images.githubusercontent.com/8122264/200033311-7f61d3f6-e45a-4b34-a1f7-7c355d15e9ae.png)

**Comment by BlackStartx** [comment]
Hi Buddy~ :3

I'll type this only to inform future people visiting this issue ticket~ 
(Maybe for curiosity or maybe due to other TMP feedback)

This issue has been addressed on the 3.8.0 version which is now public and not a candidate anymore~

I'll close the issue so, thanks so much for the feedback~ ^-^ ♥
