### ISSUE TITLE
[Request] VPM support

### ISSUE THREAD

**Issue by Andazeus** [BlackStartx/VRC-Gesture-Manager#15]
Hey there!

As you have probably heard, VRC will enforce use of the Creator Companion starting next year.

It comes with the ability to create project templates that can automatically pull packages and insert them into new projects as well as automatically update packages.

Custom repositories and packages are supported as well, but in order to take advantage of most of the advanced automation features, packages need to be provided in the VPM format. Tooling and documentation on creating a VPM package is provided here:
https://github.com/vrchat-community/template-package

Since I consider Gesture Manager to be an essential tools for avatar creation and debugging, I would love for it to be available as a custom VPM repo to be able to keep it included in my projects and updated automatically.

Are there any plans on looking into that functionality?

**Comment by BlackStartx** [comment]
Hi Andazeus~ 🌺 

I'm already working on that and I can assure you, once version 3.8 comes out, my whole repository will change to support the VPM format~ ✨ 

I'm planing to ship the new version with the repository upgrade real real soon~ ;3

**Comment by Andazeus** [comment]
Fantastic news! Thank you so much! 👍

**Comment by BlackStartx** [comment]
Hi Andazeus~

I've left this issue open even if I had already converted my tool to a VPM Package a few weeks ago~
That's because I was waiting to actually become a Curated Package, downloadable from the VCC~ ^-^ ♥

Now, after 17 days, that milestone is reached and you can import the package from the VRChat Companion App~

Thanks for the feedback, I'll close the issue~ :3 ♥
