### ISSUE TITLE
Rich Text Support

### ISSUE THREAD

**Issue by Myrkie** [BlackStartx/VRC-Gesture-Manager#2]
https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html

VRChats action menu fully supports rich text in an undocumented state if you use color codes such as below, you will beable to recolor the text without requiring the use of game modifications could you enable rich text for the menus because without it the names are excessively long, as compared to ingame when its properly applied as color
![image](https://user-images.githubusercontent.com/20288698/147397587-2d764929-03af-4603-badb-0409af57a3bd.png)

<color=green></color>

Or

<color=blue></color>

![image](https://user-images.githubusercontent.com/20288698/147397475-3d6f5e1e-46b7-4bef-a258-6ed9b86844ec.png)

![image](https://user-images.githubusercontent.com/20288698/147397481-51153d62-0262-40e7-8605-e1275682609c.png)

**Comment by BlackStartx** [comment]
Hi Myrkie~

Thanks for pointing this out!
I was not aware of this behaviour and I will definitely add the support for it!

P.S: Sorry for the late reply... I tought I had notification on but they where not and I stood upon this issue today :c
I'll release a UnityPackage of my tool with this feature enabled here as soon as possible!

Thanks again and sorry for the late reply~ ♥

**Comment by Myrkie** [comment]
> Hi Myrkie~
> 
> Thanks for pointing this out! I was not aware of this behaviour and I will definitely add the support for it!
> 
> P.S: Sorry for the late reply... I tought I had notification on but they where not and I stood upon this issue today :c I'll release a UnityPackage of my tool with this feature enabled here as soon as possible!
> 
> Thanks again and sorry for the late reply~ ♥

Hi hi I don't think to many people are aware of it and think its a effect of using a modified game thank you for adding the support and its fine that it took awhile for your response.

**Comment by BlackStartx** [comment]
Hi Myrkie, 
I'm back with a quick update!

The Radial Menu uses the Text component from the TextMeshPro library.
That component offers an **extremely wide** tag support.

Here is the documentation: http://digitalnativestudios.com/textmeshpro/docs/rich-text/

And they do all work on VRChat as well, here there are some of them:

![image](https://user-images.githubusercontent.com/26898122/147994156-3d5f53f2-c534-4746-926e-a9840b3f4b26.png)

They can even be kinda annoying if you push them to the limit:

![image](https://user-images.githubusercontent.com/26898122/147994059-d799ceab-cdc0-4d29-b8aa-7a15aa8d7efe.png)

I guess the reason it's not documented is because it's an "unintentional feature" due to the support not beeing disabled for the Radial Menu in the first place (?)

This could mean that the RichText support could either be disabled (I hope not since it's an interesting feature), or be polished out and be officially implemented.

By the way, I don't wanna leave you with the extremely long text in the menu, so tomorrow I will develp a version that support 3 tags:
- color
- bold
- italic

I will publish the package here once it's done~ ^-^

**Comment by Myrkie** [comment]
hi thanks for looking into it, as I said its an undocumented feature all of vrchats new UI all use text mesh pro aswell as the new UIElements UIToolkit format using USS and UXML [UIToolkit-Unity-2019.4](https://docs.unity3d.com/2019.4/Documentation/Manual/UIElements.html) 
so that would explain the behavior ill close this issue now, cheers.

**Comment by BlackStartx** [comment]
Hi Myrkie!

I've created a version of the tool which support common tags like:
- color
- b
- i
- mark

You can download it here: [GestureManager3.3.zip](https://github.com/BlackStartx/VRC-Gesture-Manager/files/7808553/GestureManager3.3.zip)
If this feature will get documented I will definitely support the tags in a public release as well ^-^

P.S: The file is a .zip cause Git do not support .unityPackages in issues threads.

**Comment by Myrkie** [comment]
> Hi Myrkie!
> 
> I've created a version of the tool which support common tags like:
> 
> * color
> * b
> * i
> * mark
> 
> You can download it here: [GestureManager3.3.zip](https://github.com/BlackStartx/VRC-Gesture-Manager/files/7808553/GestureManager3.3.zip) If this feature will get documented I will definitely support the tags in a public release as well ^-^
> 
> P.S: The file is a .zip cause Git do not support .unityPackages in issues threads.

thank you very much.
