### ISSUE TITLE
GestureWeight should default to 0

### ISSUE THREAD

**Issue by ShaunDreclin** [BlackStartx/VRC-Gesture-Manager#24]
Every time I test my avatars I have to drag the weight sliders to 0 to get them to a "neutral" state. I think it would make more sense for 0 to be the default, just like all of the gestures are unchecked by default.

https://github.com/BlackStartx/VRC-Gesture-Manager/assets/5851433/cd8494bc-5268-4b94-83b5-3604d4e92af8

Edit: Alternatively, if you don't want to change the default, just having the selected weight save between tests would also solve my issue.

**Comment by BlackStartx** [comment]
Hi Shaun, sorry for the late reply~ 🌺

By the way yeah, that's an inconsistency between the client and my tool, will definetly be fixed in the next release!

Dunno if I'll make it act like in-game, where having no gesture selected sets it to `0`, BUT selecting a gesture sets it to `100`~
I think this way would fit the best?
###### (This is the behaviour VRChat have while playing in Desktop)
<br>

Thanks and sorry once again~ ♥

**Comment by ShaunDreclin** [comment]
No worries! Yeah, making it behave like desktop mode probably makes the most sense
