### ISSUE TITLE
Incompatible with tools applied on play

### ISSUE THREAD

**Issue by anatawa12** [BlackStartx/VRC-Gesture-Manager#26]
There are many tools to modify avatar non-destructively on build time and many tools applies those tool on entering Play mode.
Those tools are applied during scene load (on Awake).
However, Gesture Manager initializes on OnEnable of Editor, which can be before Awake.
So, I want GestureManager to delay initialization of GM after Scene load.
For example, first OnInspectorGUI (or other IMGUI Callbacks) can be a place because it will be called after Scene load.

**Comment by BlackStartx** [comment]
Hi Anatawa~ :3 🌺 

I've officially Pre-Relased the new 3.8.5 version of my tool with the fix for allow non-destructively onBuild/onPlay tools to perform their operation before the Initialization of the Gesture Manager~ ^-^

This is done by both moving the initialization start on an IMGUI callback, but also by yielding the call a whole frame.

Once you will use the new version, please tell me if this has done the trick~ ♥ 
(No pressure... also the new version is currently in a pre-release state ^-^)

Thanks for the report,
- BlackStartx
