### ISSUE TITLE
Parameter coercion should work for built-ins

### ISSUE THREAD

**Issue by SenkyDragon** [BlackStartx/VRC-Gesture-Manager#43]
Built-in params, such as GestureLeft and GestureRight, should also work with parameter coercion. While it is unusual to do so, sometimes built-ins are used with the wrong type (int instead of bool, float instead of int, etc). In game and Av3emu handle this properly, but it seems the Gesture Manager does not. It at least does not coerce GestureLeft and GestureRight properly.

**Comment by BlackStartx** [comment]
Hi Senky~ 🌺 
Sorry for the late reply, was busy with another project!

By the way, I've havent created much avatars that revolve around **parameter coercion** so that behavior has definitely slipped trough uncontrolled and I will fix it with the release of 3.9.0~

Sorry for the troubles this may cause in some setups~ :c

###### P.S: It could be that all parameters lack of parameter coercion management, I'll do my tests and come back with updates!

**Comment by SenkyDragon** [comment]
bump

**Comment by SenkyDragon** [comment]
Apparently it also breaks gesture manager if the same parameter is present in multiple controllers with different types. Coercion should happen on a per-controller basis.

**Comment by BlackStartx** [comment]
Hi Senko~ :3 🌸

Just a quick update!

I think I'll still release a minor version before 3.9.0, and it will be just bug/issue fixing~ 👍🏻

This will allow me to prioritize stability before the overhaul I'm planing for 3.9.0, who's gonna take longer!

Before the curated update request I may also share beta builds here, just in case you wish to confirm that everything is fine! ^-^

Also... Sorry once again for the delay of the fix~ :c

Thanks for all the informations!
- BlackStartx :3

**Comment by BlackStartx** [comment]
I'll close the issues since 3.8.9 is now officially downloadable from the VCC~

If there are other issues feel free to open another issue! :3
